//! Tests that a column the database will never let hold nothing is reported
//! that way, whichever route the requirement arrives by.
//!
//! Three answers used to be wrong. An identity column reported that it accepted
//! nothing at all. A child reported its column as accepting nothing whenever
//! the parent's key was written as a table constraint or added later, because a
//! child inherits column options and not its parent's key. And every column of
//! a multi-column key answered that it was not part of one, because the
//! predicate asked whether *all* of the key's columns were the one being asked
//! about rather than whether *any* of them was.
//!
//! Every expectation was measured against PostgreSQL 18.4. The load-bearing one
//! is that PostgreSQL keeps the requirement as a constraint in its own right
//! rather than as a shadow of the key, so dropping the key afterwards leaves
//! the column still requiring a value. This crate mirrors that by writing the
//! requirement onto the column when the key or the identity is declared.
#![allow(clippy::expect_used)]

use sql_traits::prelude::*;
use sqlparser::dialect::PostgreSqlDialect;

fn database(sql: &str) -> ParserDB {
    ParserDB::parse::<PostgreSqlDialect>(sql).expect("schema parses")
}

fn accepts_nothing(database: &ParserDB, table_name: &str, column_name: &str) -> bool {
    !database
        .table(None, table_name)
        .expect("table exists")
        .column(column_name, database)
        .expect("lookup succeeds")
        .expect("column exists")
        .is_nullable(database)
        .expect("table is in this database")
}

#[test]
fn an_identity_column_requires_a_value() {
    let database = database(
        "CREATE TABLE t (
             always INT GENERATED ALWAYS AS IDENTITY,
             by_default INT GENERATED BY DEFAULT AS IDENTITY,
             plain INT,
             computed INT GENERATED ALWAYS AS (1) STORED
         );",
    );

    for column in ["always", "by_default"] {
        assert!(accepts_nothing(&database, "t", column), "{column} must require a value");
    }
    assert!(!accepts_nothing(&database, "t", "plain"));
    // A computed column is not an identity and PostgreSQL leaves it nullable.
    assert!(!accepts_nothing(&database, "t", "computed"));
}

#[test]
fn a_child_requires_a_value_however_the_parents_key_was_written() {
    // The parent answers correctly under every spelling, so before this the two
    // tables disagreed about one column.
    for sql in [
        "CREATE TABLE par (id INT PRIMARY KEY);
         CREATE TABLE chi () INHERITS (par);",
        "CREATE TABLE par (id INT, CONSTRAINT p1 PRIMARY KEY (id));
         CREATE TABLE chi () INHERITS (par);",
        "CREATE TABLE par (id INT);
         CREATE TABLE chi () INHERITS (par);
         ALTER TABLE par ADD CONSTRAINT p1 PRIMARY KEY (id);",
    ] {
        let database = database(sql);
        assert!(accepts_nothing(&database, "par", "id"));
        assert!(accepts_nothing(&database, "chi", "id"), "child disagrees for:\n{sql}");
    }
}

#[test]
fn a_key_added_later_reaches_a_grandchild_too() {
    // The key itself stays with the parent, because an `INHERITS` child
    // receives no key, but the requirement it implies travels the whole
    // chain.
    let database = database(
        "CREATE TABLE par (id INT, code TEXT);
         CREATE TABLE chi () INHERITS (par);
         CREATE TABLE gch () INHERITS (chi);
         ALTER TABLE par ADD CONSTRAINT p1 PRIMARY KEY (id);",
    );

    for table in ["par", "chi", "gch"] {
        assert!(accepts_nothing(&database, table, "id"), "{table} disagrees");
        assert!(!accepts_nothing(&database, table, "code"));
    }
    // Only the parent holds the key.
    assert_eq!(
        database
            .table(None, "chi")
            .expect("table exists")
            .primary_key_columns(&database)
            .expect("in database")
            .count(),
        0
    );
}

#[test]
fn the_requirement_outlives_the_key_that_implied_it() {
    // PostgreSQL records it as a constraint of its own, so dropping the key
    // leaves the column still unable to hold nothing.
    let database = database(
        "CREATE TABLE par (id INT, CONSTRAINT p1 PRIMARY KEY (id));
         CREATE TABLE chi () INHERITS (par);
         ALTER TABLE par DROP CONSTRAINT p1;",
    );

    assert_eq!(
        database
            .table(None, "par")
            .expect("table exists")
            .primary_key_columns(&database)
            .expect("in database")
            .count(),
        0
    );
    assert!(accepts_nothing(&database, "par", "id"));
    assert!(accepts_nothing(&database, "chi", "id"));
}

#[test]
fn every_column_of_a_multi_column_key_belongs_to_it() {
    let database = database("CREATE TABLE pair (a INT, b INT, c INT, PRIMARY KEY (a, b));");
    let pair = database.table(None, "pair").expect("table exists");

    for name in ["a", "b"] {
        let column = pair.column(name, &database).expect("lookup").expect("column exists");
        assert!(pair.is_primary_key_column(&database, column).expect("in database"), "{name}");
        assert!(accepts_nothing(&database, "pair", name), "{name}");
    }

    let c = pair.column("c", &database).expect("lookup").expect("column exists");
    assert!(!pair.is_primary_key_column(&database, c).expect("in database"));
    assert!(!accepts_nothing(&database, "pair", "c"));
}

#[test]
fn a_table_with_no_key_has_no_key_columns() {
    // The predicate used to answer `true` for any column of a keyless table,
    // which an emptiness guard beside it was covering up.
    let database = database("CREATE TABLE plain (a INT, b INT);");
    let plain = database.table(None, "plain").expect("table exists");

    for name in ["a", "b"] {
        let column = plain.column(name, &database).expect("lookup").expect("column exists");
        assert!(!plain.is_primary_key_column(&database, column).expect("in database"), "{name}");
    }
}

#[test]
fn an_explicit_null_gives_way_to_the_requirement() {
    // `id INT NULL PRIMARY KEY` is accepted by PostgreSQL and the key wins.
    let database = database("CREATE TABLE t (id INT NULL, CONSTRAINT p1 PRIMARY KEY (id));");
    assert!(accepts_nothing(&database, "t", "id"));
}

#[test]
fn a_partition_requires_what_its_root_requires() {
    let database = database(
        "CREATE TABLE root (id INT, code TEXT) PARTITION BY RANGE (id);
         CREATE TABLE part PARTITION OF root FOR VALUES FROM (1) TO (9);
         ALTER TABLE root ADD CONSTRAINT p1 PRIMARY KEY (id);",
    );

    for table in ["root", "part"] {
        assert!(accepts_nothing(&database, table, "id"), "{table}");
        assert!(!accepts_nothing(&database, table, "code"));
    }
    // Unlike an inheritor, a partition receives the key itself as well.
    assert_eq!(
        database
            .table(None, "part")
            .expect("table exists")
            .primary_key_columns(&database)
            .expect("in database")
            .count(),
        1
    );
}

#[test]
fn a_schema_that_never_required_a_value_is_left_alone() {
    // Guards against the requirement being written onto columns a key does not
    // cover, which would make almost every column answer wrongly.
    let database = database(
        "CREATE TABLE t (id INT PRIMARY KEY, code TEXT, note TEXT DEFAULT 'x', tally INT UNIQUE);",
    );

    assert!(accepts_nothing(&database, "t", "id"));
    for column in ["code", "note", "tally"] {
        assert!(!accepts_nothing(&database, "t", column), "{column} must stay optional");
    }
}
