type ScalarFamilyCase = (&'static str, Option<ScalarFamily>);

const FAMILY_CASES: &[ScalarFamilyCase] = &[
    ("INT", Some(ScalarFamily::Int)),
    ("integer", Some(ScalarFamily::Int)),
    ("SMALLINT", Some(ScalarFamily::Int)),
    ("bigint", Some(ScalarFamily::Int)),
    ("TINYINT", Some(ScalarFamily::Int)),
    ("MEDIUMINT", Some(ScalarFamily::Int)),
    ("int2", Some(ScalarFamily::Int)),
    ("INT4", Some(ScalarFamily::Int)),
    ("INT8", Some(ScalarFamily::Int)),
    ("SERIAL", Some(ScalarFamily::Int)),
    ("smallserial", Some(ScalarFamily::Int)),
    ("BIGSERIAL", Some(ScalarFamily::Int)),
    ("HUGEINT", Some(ScalarFamily::Int)),
    ("hugeint", Some(ScalarFamily::Int)),
    ("INT16", Some(ScalarFamily::Int)),
    ("INT32", Some(ScalarFamily::Int)),
    ("INT64", Some(ScalarFamily::Int)),
    ("INT128", Some(ScalarFamily::Int)),
    ("INT256", Some(ScalarFamily::Int)),
    ("UINT8", Some(ScalarFamily::Int)),
    ("uint8", Some(ScalarFamily::Int)),
    ("UINT16", Some(ScalarFamily::Int)),
    ("UINT32", Some(ScalarFamily::Int)),
    ("UINT64", Some(ScalarFamily::Int)),
    ("UINT128", Some(ScalarFamily::Int)),
    ("UINT256", Some(ScalarFamily::Int)),
    ("FLOAT", Some(ScalarFamily::Float)),
    ("REAL", Some(ScalarFamily::Float)),
    ("DOUBLE", Some(ScalarFamily::Float)),
    ("DOUBLE PRECISION", Some(ScalarFamily::Float)),
    ("float4", Some(ScalarFamily::Float)),
    ("float8", Some(ScalarFamily::Float)),
    ("FLOAT32", Some(ScalarFamily::Float)),
    ("float64", Some(ScalarFamily::Float)),
    ("DECIMAL", Some(ScalarFamily::Decimal)),
    ("NUMERIC", Some(ScalarFamily::Decimal)),
    ("number", Some(ScalarFamily::Decimal)),
    ("MONEY", Some(ScalarFamily::Decimal)),
    ("BOOL", Some(ScalarFamily::Bool)),
    ("boolean", Some(ScalarFamily::Bool)),
    ("TEXT", Some(ScalarFamily::String)),
    ("VARCHAR", Some(ScalarFamily::String)),
    ("CHAR", Some(ScalarFamily::String)),
    ("CHARACTER", Some(ScalarFamily::String)),
    ("CHARACTER VARYING", Some(ScalarFamily::String)),
    ("nvarchar", Some(ScalarFamily::String)),
    ("NCHAR", Some(ScalarFamily::String)),
    ("CLOB", Some(ScalarFamily::String)),
    ("STRING", Some(ScalarFamily::String)),
    ("TINYTEXT", Some(ScalarFamily::String)),
    ("tinytext", Some(ScalarFamily::String)),
    ("MEDIUMTEXT", Some(ScalarFamily::String)),
    ("LONGTEXT", Some(ScalarFamily::String)),
    ("FIXEDSTRING", Some(ScalarFamily::String)),
    ("fixedstring", Some(ScalarFamily::String)),
    ("BYTEA", Some(ScalarFamily::Bytes)),
    ("BLOB", Some(ScalarFamily::Bytes)),
    ("binary", Some(ScalarFamily::Bytes)),
    ("VARBINARY", Some(ScalarFamily::Bytes)),
    ("BYTES", Some(ScalarFamily::Bytes)),
    ("TINYBLOB", Some(ScalarFamily::Bytes)),
    ("tinyblob", Some(ScalarFamily::Bytes)),
    ("MEDIUMBLOB", Some(ScalarFamily::Bytes)),
    ("LONGBLOB", Some(ScalarFamily::Bytes)),
    ("DATE", Some(ScalarFamily::Date)),
    ("date", Some(ScalarFamily::Date)),
    ("DATE32", Some(ScalarFamily::Date)),
    ("date32", Some(ScalarFamily::Date)),
    ("TIME", Some(ScalarFamily::Time)),
    ("TIME WITHOUT TIME ZONE", Some(ScalarFamily::Time)),
    ("TIME WITH TIME ZONE", Some(ScalarFamily::Time)),
    ("timetz", Some(ScalarFamily::Time)),
    ("TIMESTAMP", Some(ScalarFamily::Timestamp)),
    ("TIMESTAMP WITHOUT TIME ZONE", Some(ScalarFamily::Timestamp)),
    ("DATETIME", Some(ScalarFamily::Timestamp)),
    ("DATETIME64", Some(ScalarFamily::Timestamp)),
    ("datetime64", Some(ScalarFamily::Timestamp)),
    ("TIMESTAMPTZ", Some(ScalarFamily::TimestampTz)),
    ("timestamptz", Some(ScalarFamily::TimestampTz)),
    ("TIMESTAMP WITH TIME ZONE", Some(ScalarFamily::TimestampTz)),
    ("timestamp with time zone", Some(ScalarFamily::TimestampTz)),
    ("TIMESTAMP WITH TIMEZONE", Some(ScalarFamily::TimestampTz)),
    ("timestamp with timezone", Some(ScalarFamily::TimestampTz)),
    ("UUID", Some(ScalarFamily::Uuid)),
    ("uuid", Some(ScalarFamily::Uuid)),
    ("JSON", Some(ScalarFamily::Json)),
    ("json", Some(ScalarFamily::Json)),
    ("JSONB", Some(ScalarFamily::Jsonb)),
    ("jsonb", Some(ScalarFamily::Jsonb)),
];

const DECORATED_CASES: &[ScalarFamilyCase] = &[
    ("VARCHAR(255)", Some(ScalarFamily::String)),
    ("NUMERIC(20, 4)", Some(ScalarFamily::Decimal)),
    ("DECIMAL(10,2)", Some(ScalarFamily::Decimal)),
    ("TIMESTAMP(6) WITH TIME ZONE", Some(ScalarFamily::TimestampTz)),
    ("TIMESTAMP WITHOUT TIME ZONE", Some(ScalarFamily::Timestamp)),
    ("CHARACTER VARYING(16)", Some(ScalarFamily::String)),
    ("BIGINT UNSIGNED", Some(ScalarFamily::Int)),
    ("VaRcHaR(255)", Some(ScalarFamily::String)),
    ("  VARCHAR(255)  ", Some(ScalarFamily::String)),
    ("TIMESTAMP  ( 6 )   WITH   TIME  ZONE", Some(ScalarFamily::TimestampTz)),
    ("CHARACTER\tVARYING ( 16 )", Some(ScalarFamily::String)),
    ("DOUBLE   PRECISION", Some(ScalarFamily::Float)),
];

const QUOTED_POSTGRES_CASES: &[ScalarFamilyCase] = &[
    ("\"int2\"", Some(ScalarFamily::Int)),
    ("\"smallint\"", Some(ScalarFamily::Int)),
    ("\"smallserial\"", Some(ScalarFamily::Int)),
    ("\"int4\"", Some(ScalarFamily::Int)),
    ("\"integer\"", Some(ScalarFamily::Int)),
    ("\"serial\"", Some(ScalarFamily::Int)),
    ("\"int8\"", Some(ScalarFamily::Int)),
    ("\"bigint\"", Some(ScalarFamily::Int)),
    ("\"bigserial\"", Some(ScalarFamily::Int)),
    ("\"float4\"", Some(ScalarFamily::Float)),
    ("\"real\"", Some(ScalarFamily::Float)),
    ("\"float8\"", Some(ScalarFamily::Float)),
    ("\"double precision\"", Some(ScalarFamily::Float)),
    ("\"numeric\"", Some(ScalarFamily::Decimal)),
    ("\"decimal\"", Some(ScalarFamily::Decimal)),
    ("\"bool\"", Some(ScalarFamily::Bool)),
    ("\"boolean\"", Some(ScalarFamily::Bool)),
    ("\"varchar\"", Some(ScalarFamily::String)),
    ("\"VARCHAR\"", Some(ScalarFamily::String)),
    ("\"character varying\"", Some(ScalarFamily::String)),
    ("\"char\"", Some(ScalarFamily::String)),
    ("\"character\"", Some(ScalarFamily::String)),
    ("\"text\"", Some(ScalarFamily::String)),
    ("  \"text\"  ", Some(ScalarFamily::String)),
    ("\"date\"", Some(ScalarFamily::Date)),
    ("\"uuid\"", Some(ScalarFamily::Uuid)),
    ("\"timestamp\"", Some(ScalarFamily::Timestamp)),
    ("\"timestamp without time zone\"", Some(ScalarFamily::Timestamp)),
    ("\"timestamptz\"", Some(ScalarFamily::TimestampTz)),
    ("\"timestamp with time zone\"", Some(ScalarFamily::TimestampTz)),
    ("\"time\"", Some(ScalarFamily::Time)),
    ("\"time without time zone\"", Some(ScalarFamily::Time)),
    ("\"timetz\"", Some(ScalarFamily::Time)),
    ("\"time with time zone\"", Some(ScalarFamily::Time)),
    ("\"bytea\"", Some(ScalarFamily::Bytes)),
];

const QUOTED_REJECTED_CASES: &[ScalarFamilyCase] = &[
    ("\"custom_type\"", None),
    ("\"custom type\"", None),
    ("\"public.custom_type\"", None),
    ("\"varchar\"[]", None),
    ("\"\"varchar\"\"", None),
];

const REJECTED_CASES: &[ScalarFamilyCase] = &[
    ("", None),
    ("geometry", None),
    ("INTERVAL  YEAR  TO  MONTH", None),
    ("GEOMETRY(Point, 4326)", None),
    ("VARCHAR[]", None),
    ("TIMESTAMP WITH LOCAL TIME ZONE", None),
];

fn all_scalar_family_cases() -> impl Iterator<Item = ScalarFamilyCase> {
    FAMILY_CASES
        .iter()
        .chain(DECORATED_CASES.iter())
        .chain(QUOTED_POSTGRES_CASES.iter())
        .chain(QUOTED_REJECTED_CASES.iter())
        .chain(REJECTED_CASES.iter())
        .copied()
}
