//! Whether a column option makes the column an identity column.

use sqlparser::ast::ColumnOption;

/// Returns whether the option makes the column an identity column.
///
/// `GENERATED ... AS IDENTITY` and `GENERATED ... AS (expr) STORED` share one
/// variant and are told apart by whether an expression is present. Other
/// dialects spell the same idea as a variant of its own.
///
/// # Examples
///
/// ```
/// use sql_traits::utils::is_identity;
/// use sqlparser::{
///     ast::{ColumnOption, Statement},
///     dialect::PostgreSqlDialect,
///     parser::Parser,
/// };
///
/// let parse = |sql: &str| {
///     let statements = Parser::parse_sql(&PostgreSqlDialect {}, sql).expect("parses");
///     let Some(Statement::CreateTable(create_table)) = statements.into_iter().next() else {
///         panic!("not a CREATE TABLE");
///     };
///     create_table.columns[0].options[0].option.clone()
/// };
///
/// assert!(is_identity(&parse("CREATE TABLE t (a INT GENERATED ALWAYS AS IDENTITY)")));
/// assert!(is_identity(&parse("CREATE TABLE t (a INT GENERATED BY DEFAULT AS IDENTITY)")));
///
/// // A computed column is generated but is not an identity.
/// assert!(!is_identity(&parse("CREATE TABLE t (a INT GENERATED ALWAYS AS (1) STORED)")));
/// assert!(!is_identity(&ColumnOption::NotNull));
/// ```
#[must_use]
pub fn is_identity(option: &ColumnOption) -> bool {
    match option {
        ColumnOption::Identity(_) => true,
        ColumnOption::Generated { generation_expr, .. } => generation_expr.is_none(),
        _ => false,
    }
}
