name: Links

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2
        with:
          # Check all markdown and rust files
          args: >
            --verbose
            --no-progress
            --exclude 'https://codecov.io/gh/earth-metabolome-initiative/sql-traits'
            --exclude 'https://codecov.io/gh/earth-metabolome-initiative/sql-traits/branch/main/graph/badge.svg'
            './**/*.md' './**/*.rs'
          # Fail the action if broken links are found
          fail: true
